@baseUrl = http://localhost:3000

# RECADOS
### LISTA TODOS OS RECADOS
GET {{baseUrl}}/recados/
?limit=10
&offset=0
### LISTA UM RECADO
GET {{baseUrl}}/recados/9/
### CRIA UM RECADO
POST {{baseUrl}}/recados/
Content-Type: application/json

{
    "texto": "de 11 para 10",
    "deId": 11,
    "paraId": 10
}
### ATUALIZA UM RECADO
PATCH {{baseUrl}}/recados/9/
Content-Type: application/json

{
    "texto": "bla bla",
    "lido": true
}
### APAGA UM RECADO
DELETE {{baseUrl}}/recados/3/


#


# Pessoas
### LISTA TODAS AS PESSOAS
GET {{baseUrl}}/pessoas/
?limit=100&offset=0
### LISTA UM Pessoa
GET {{baseUrl}}/pessoas/7/
### CRIA UM Pessoa
POST {{baseUrl}}/pessoas/
Content-Type: application/json

{
    "email": "zezin@email.com",
    "password": "123456",
    "nome": "zezin"
}
### ATUALIZA UMA PESSOA
PATCH {{baseUrl}}/pessoas/7/
Content-Type: application/json

{
    "password": "12345678",
    "nome": "Matheus M"
}
### APAGA UMA PESSOA
DELETE {{baseUrl}}/pessoas/9/


#


### AppControllerGetHello 

 # @name AppControllerGetHello
 GET {{baseUrl}}/home/hello/

### Exemplo de Rota

 # @name ExemploDeRota
 GET  {{baseUrl}}/home/exemplo/

### ConceitosManualController Home

 # @name ConceitosManualControllerHome
 GET  {{baseUrl}}/conceitos-manual/

### ConceitosAutomaticoController Home

 # @name ConceitosAutomaticoControllerHome
 GET  {{baseUrl}}/conceitos-automatico/