@baseUrl = http://localhost:3000

# RECADOS
### LISTA TODOS OS RECADOS
GET {{baseUrl}}/recados/
?limit=100&offset=0
### LISTA UM RECADO
GET {{baseUrl}}/recados/2/
### CRIA UM RECADO
POST {{baseUrl}}/recados/
Content-Type: application/json

{
    "texto": "Novo recado",
    "de": "Joana",
    "para": "João"
}
### ATUALIZA UM RECADO
PATCH {{baseUrl}}/recados/2/
Content-Type: application/json

{
    "texto": "Atualizar1 recado"
}
### APAGA UM RECADO
DELETE {{baseUrl}}/recados/3/


#


# Pessoas
### LISTA TODAS AS PESSOAS
GET {{baseUrl}}/pessoas/
?limit=100&offset=0
### LISTA UM Pessoa
GET {{baseUrl}}/pessoas/2/
### CRIA UM Pessoa
POST {{baseUrl}}/pessoas/
Content-Type: application/json

{
    "email": "email1@email.com",
    "password": "123456",
    "nome": "Matheus"
}
### ATUALIZA UMA PESSOA
PATCH {{baseUrl}}/pessoas/2/
Content-Type: application/json

{
    "texto": "Atualizar1 recado"
}
### APAGA UMA PESSOA
DELETE {{baseUrl}}/pessoas/4/


#


### AppControllerGetHello 

 # @name AppControllerGetHello
 GET {{baseUrl}}/home/hello/

### Exemplo de Rota

 # @name ExemploDeRota
 GET  {{baseUrl}}/home/exemplo/

### ConceitosManualController Home

 # @name ConceitosManualControllerHome
 GET  {{baseUrl}}/conceitos-manual/

### ConceitosAutomaticoController Home

 # @name ConceitosAutomaticoControllerHome
 GET  {{baseUrl}}/conceitos-automatico/