@baseUrl = http://localhost:3000

# RECADOS
### LISTA TODOS OS RECADOS
GET {{baseUrl}}/recados/
### LISTA UM RECADO
GET {{baseUrl}}/recados/1/
### CRIA UM RECADO
POST {{baseUrl}}/recados/
Content-Type: application/json

{
    "recado": "Este é o racado q estou enviando",
    "nova chave": "outro valor"
}
### ATUALIZA UM RECADO
PATCH {{baseUrl}}/recados/1/
Content-Type: application/json

{
    "recado": "Este é o racado q estou enviando",
    "atualizar": true
}
### APAGA UM RECADO
DELETE {{baseUrl}}/recados/1/



### AppControllerGetHello 

 # @name AppControllerGetHello
 GET {{baseUrl}}/home/hello/

### Exemplo de Rota

 # @name ExemploDeRota
 GET  {{baseUrl}}/home/exemplo/

### ConceitosManualController Home

 # @name ConceitosManualControllerHome
 GET  {{baseUrl}}/conceitos-manual/

### ConceitosAutomaticoController Home

 # @name ConceitosAutomaticoControllerHome
 GET  {{baseUrl}}/conceitos-automatico/